### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by pitcons**

### CODE REVIEW

**Comment by cladden** [comment]
@Mulugruntz does this PR look okay to merge?

**Comment by Mulugruntz** [comment]
Hi,
@cladden @pitcons @paulochf
sorry for the extreme delay!
Could you please add at least one py3 engine in `.travis.yml`? And rerun the checks.

**Comment by Mulugruntz** [comment]
And please check this relative import is actually needed.
Don't you have an issue in your PYTHON_PATH?
I'm not sure exactly how py3 works for this.

**Comment by paulochf** [comment]
> And please check this relative import is actually needed.
> Don't you have an issue in your PYTHON_PATH?
> I'm not sure exactly how py3 works for this.

Unfortunately, I don't know how to do this. :cry:

**Comment by Mulugruntz** [comment]
Okay, I've (finally) checked it and it seems that adding this dot makes it work. 
Next to be done:
In `setup.py`, in classifiers, it should not be Py2 only anymore, and py3 classifier can be added.
In `.travis.yml`, python 3.6 can be added so that it checks on both environments

I think that's it.

And sorry for my super slow response time!

**Comment by Mulugruntz** [comment]
And bumping the version in `setup.py` to `0.1.5`
And adding into `README.md` and `README.rst`:
```
* 0.1.5
    * Python 3 compatibility
```

**Comment by Mulugruntz** [comment]
@pitcons If you can do that, your name will be on it.
Otherwise, if you're too busy for it, I'll just cherry-pick it some day (not sure when) to keep your name on it.

**Comment by Mulugruntz** [comment]
Done. Version is now `0.1.6` and is on PyPI: https://pypi.python.org/pypi/celery_pubsub

**Pull request merged**
