### PR TITLE
add typing

### PR DESCRIPTION
**Pull request by WaYdotNET**
Add typing to pubsub.py

### CODE REVIEW

**Comment by Mulugruntz** [comment]
Thanks @WaYdotNET for your help!

As it is now, I see several areas of improvement:
1. This typing only works in Python 3. Two possibilities:
    1. Mypy can also work with the comment-style typing, compatible with Python 2.
    2. There is also the `.pyi` files (python stubs): https://peps.python.org/pep-0484/#stub-files
2. If we do want to drop support for older versions, then it's not a `1.0.0 -> 1.0.1` bump, but this would be a `1.0.0 -> 2.0.0` bump instead.
3. The heavy use of `Any`. It's akin to telling mypy: just skip it. It's not actual type hinted. If I had to guess, I'd say you had to rename `result` to `_result`, to actually ignore the type hinting altogether, because `mypy` was starting to analyze those functions. I haven't checked, but when I see `AyncResult[Any]`, I'm, guessing it's because it's a generic. If so, we should propagate it instead of making it `Any`. **Edit: nope, there's no generics. Had to remove all of them**
4. Same for `: object`.
5. In `requirements_test.txt`, we could add `celery-stubs`.
6. `from __future__ import annotations` is only available since `Python 3.7.0 beta 1`. That's a lot of version where the support would be dropped.

After a few tweaks here and there, and running `stubgen` (comes with `mypy`) and changing a few stuff again, I get the following `.pyi` file:
```python
from celery import Task, group
from celery.result import AsyncResult
from typing import Any
import re

class PubSubManager:
    subscribed: set[tuple[str, re.Pattern[str], Task]]
    jobs: dict[str, group]
    def __init__(self) -> None: ...
    def publish(self, topic: str, *args: Any, **kwargs: Any) -> AsyncResult: ...
    def publish_now(self, topic: str, *args: Any, **kwargs: Any) -> AsyncResult: ...
    def subscribe(self, topic: str, task: Task) -> None: ...
    def unsubscribe(self, topic: str, task: Task) -> None: ...
    def get_jobs(self, topic: str) -> group: ...

def publish(topic: str, *args: Any, **kwargs: Any) -> AsyncResult: ...
def publish_now(topic: str, *args: Any, **kwargs: Any) -> AsyncResult: ...
def subscribe(topic: str, task: Task) -> None: ...
def unsubscribe(topic: str, task: Task) -> None: ...
```

**Comment by WaYdotNET** [comment]
Hi @Mulugruntz , i've add `strict = True` to mypy config and fix some code (thx to reply)

```python
import re
from celery import Task, group
from celery.result import AsyncResult
from typing import Any

class PubSubManager:
    subscribed: set[tuple[str, re.Pattern[str], Task[Any, Any]]]
    jobs: dict[str, group]
    def publish(self, topic: str, *args: Any, **kwargs: Any) -> AsyncResult[Any]: ...
    def publish_now(self, topic: str, *args: Any, **kwargs: Any) -> AsyncResult[Any]: ...
    def subscribe(self, topic: str, task: Task[Any, Any]) -> None: ...
    def unsubscribe(self, topic: str, task: Task[Any, Any]) -> None: ...
    def get_jobs(self, topic: str) -> group: ...

def publish(topic: str, *args: Any, **kwargs: Any) -> AsyncResult[Any]: ...
def publish_now(topic: str, *args: Any, **kwargs: Any) -> AsyncResult[Any]: ...
def subscribe(topic: str, task: Task[Any, Any]) -> None: ...
def unsubscribe(topic: str, task: Task[Any, Any]) -> None: ...

```

**Comment by Mulugruntz** [comment]
Hi @WaYdotNET ,

It seems the `pyi` file is missing. Did you push it?
And the `py` file should not have type hints. This way, it'll work for both py2 and py3.

**Comment by WaYdotNET** [comment]
@Mulugruntz up

**Comment by Mulugruntz** [comment]
Hi @WaYdotNET !

Did you see the comments I left previously? :-) 

These need to be addressed first (or discussed, if you think they're not justified).

Almost there! :-)

**Comment by WaYdotNET** [comment]
Hi @Mulugruntz , i've already add stub file (pyi) and remove typing from source file (andh fix changelog)

**Comment by Mulugruntz** [comment]
Hi @WaYdotNET .

I still see changes on the source file: https://github.com/Mulugruntz/celery-pubsub/pull/177/files#diff-ff68528a826d175638283b3562e35d1f9ef1198357bcba1c55fbf4a9416ad480L1

Can you check that you pushed your changes? ;-)

**Comment by WaYdotNET** [comment]
Hi @Mulugruntz rollback change and apply black

**Comment by Mulugruntz** [comment]
Created issue #186 to reference this.

**Comment by Mulugruntz** [comment]
Thanks, I merged your changes! :-)
See #189

**Pull request closed without merging**
